# SPDX-License-Identifier: Apache-2.0
# Licences des dépendances Rust : uniquement compatibles Apache-2.0.
[licenses]
allow = ["Apache-2.0", "Apache-2.0 WITH LLVM-exception", "MIT", "BSD-2-Clause", "BSD-3-Clause", "ISC", "Unicode-3.0", "Zlib", "MPL-2.0", "CDLA-Permissive-2.0"]
confidence-threshold = 0.9
unused-allowed-license = "allow"

[bans]
multiple-versions = "allow"
