# SPDX-License-Identifier: Apache-2.0
line-length = 110
target-version = "py311"

[lint]
select = ["E", "F", "W", "I", "B", "UP", "S"]
ignore = ["S101"]

[lint.per-file-ignores]
"**/tests/**" = ["S105", "S106", "S107"]
"dev/**" = ["S104"]
"tests/e2e/**" = ["S603", "S607"]
