# SPDX-License-Identifier: Apache-2.0
[package]
name = "sesame-portal"
description = "Portail d'authentification Sesame : OIDC ou SAML, session portail, page « Mes applications »."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
chrono.workspace = true
sesame-core.workspace = true
sesame-store-postgres.workspace = true
axum.workspace = true
base64.workspace = true
openidconnect.workspace = true
reqwest.workspace = true
samael.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

[lints]
workspace = true
